database:
  host: "postgres.default.svc.cluster.local"
  port: "5432"
  adapter: "postgres"
  databaseName: "pactbroker"
  auth:
    username: "pactbroker"
    password: "pactbroker-password"

broker:
  imagePullSecrets:
    - my-registry-secret
  config:
    databaseClean:
      enabled: true
      mode: external
