# CI test values for the Pact Broker deployment when using an external database
# with credentials that are specified in a Kubernetes secret.
database:
  host: "postgres.default.svc.cluster.local"
  port: "5432"
  adapter: "postgres"
  databaseName: "pactbroker"
  auth:
    username: "pactbroker"
    # Using existing Kubernetes secret for password (created in ci-postgres.yaml)
    existingSecret: "pact-broker-db-secret"
    existingSecretPasswordKey: "database-password"
