{{- if and (.Values.broker.config.databaseClean.enabled) (eq .Values.broker.config.databaseClean.mode "external") }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}-dbclean
  namespace: {{ .Release.Namespace | quote }}
  labels:
    name: {{ include "chart.fullname" . }}
    app.kubernetes.io/name: {{ include "chart.name" . }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.broker.config.databaseClean.cronSchedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ template "chart.fullname" . }}-dbclean
              image: {{ template "broker.image" . }}
              imagePullPolicy: {{ .Values.broker.imagePullPolicy }}
              command:
                - clean
              env:
                # Logging
                {{- include "envVars.logging" . | nindent 16 }}
                # Database
                {{- include "envVars.db" . | nindent 16 }}
                # Database clean up (external mode)
                {{- include "envVars.dbCleanup" . | nindent 16 }}
          restartPolicy: Never
{{- end}}