name: Codespell

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: pull_request

jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Codespell
        uses: codespell-project/actions-codespell@6597c863cb3f4c3d973314d7d7b4d0e8de701480 # master
        with:
          skip: .git
          check_filenames: true
          check_hidden: true